# Identificación del proyecto
sonar.projectKey=verificacion_firma_digital_mid
sonar.projectName=verificacion_firma_digital_mid
sonar.projectVersion=1.0

# Ruta base del código fuente 
sonar.sources=.

# Incluir subdirectorios con código Go
sonar.inclusions=**/*.go

# Excluir carpetas innecesarias
sonar.exclusions=**/vendor/**, **/test/**, **/*.pb.go

# Ruta de los archivos de prueba
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Lenguaje principal
sonar.language=go
sonar.sourceEncoding=UTF-8
