appname = verificacion_firma_digital_mid
httpport = ${VERI_FIRMA_DIGITAL_MID_HTTP_PORT}
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
ProtocolAdmin = ${VERI_FIRMA_DIGITAL_MID_PROTOCOL_ADMIN}

FirmaElectronicaService = ${FIRMA_ELECTRONICA_SERVICE}
EscanearArchivo = ${ESCANEAR_ARCHIVO}
# EvaluacionDocenteService = ${EVALUACION_DOCENTE_SERVICE}


