appname = verificacion_firma_digital_mid
httpport = ${VERI_FIRMA_DIGITAL_MID_HTTP_PORT}
runmode = prod
autorender = false
copyrequestbody = true
EnableDocs = true

parameterStore = ${PARAMETER_STORE}
FirmaElectronicaService = ${FIRMA_ELECTRONICA_SERVICE}
EscanearArchivo = ${ESCANEAR_ARCHIVO}
